workflows:
  posti-android:
    name: Posti Android
    instance_type: mac_mini_m1
    max_build_duration: 60
    
    environment:
      groups:
        - android_secrets
      vars:
        ANDROID_KEYSTORE_PATH: $CM_KEYSTORE_PATH
        
    scripts:
      - name: Install Node dependencies
        script: npm install --legacy-peer-deps
          
      - name: Build Web App
        script: npm run build
          
      - name: Sync Capacitor
        script: npx cap sync android
          
      - name: Fix Gradle Wrapper
        script: |
          cd android
          rm -rf .gradle gradle/wrapper
          gradle wrapper --gradle-version 8.0
          
      - name: Fix Android Configs
        script: |
          cd android
          echo "android.useAndroidX=true" >> gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties
          sed -i '' 's/compileSdkVersion.*/compileSdkVersion 34/g' app/build.gradle
          sed -i '' 's/targetSdkVersion.*/targetSdkVersion 34/g' app/build.gradle
          sed -i '' 's/minSdkVersion.*/minSdkVersion 22/g' app/build.gradle
          
      - name: Build Debug To Show Error
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace || true
          
      - name: Build Android APK Release
        script: |
          cd android
          ./gradlew assembleRelease --stacktrace
          
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
