buildscript {
    ext {
        kotlin_version = '1.8.0'
        compileSdkVersion = 34
        targetSdkVersion = 34
        minSdkVersion = 22
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        flatDir {
            dirs 'libs'
        }
    }
}

// الحل: امنع 1.79 من المشروع كله
subprojects {
    configurations.all {
        exclude group: 'org.bouncycastle', module: 'bcprov-jdk18on'
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
