name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - run: npm install  # <-- غيرنا دي

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.2.1'

      - run: cd android && ./gradlew assembleDebug --no-daemon --stacktrace

      - uses: actions/upload-artifact@v4
        with:
          name: Posti-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
