name: Build Android APK
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: npm install

      - name: Build Web App
        run: npm run build

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Give gradlew permission  # <- ضفنا السطر ده
        run: chmod +x ./android/gradlew

      - name: Build APK
        run: cd android && ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Posti-Debug-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
